const catalogProduct = [
  {
    id: "1",
    name: "Трактор Deutz Agrotron X720",
    price: 72,
    depth: "38 см.",
    width: "18 см.",
    height: "21 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Колёса поворачиваются дополнительным рулём. Капот поднимается (открывается доступ к двигателю).	 Двери кабины открываются.
	 Передняя ось оснащена амортизатором. Фаркоп. Колёса прорезинены. В наборе трактор.
	 Вес: 1,2<br>`,
    img: "./img/optima.jpg",
    img1: "./img/optima.jpg",
    img2: "./img/img_product/C4zuU3NFOCM.jpg",
    img3: "./img/img_product/r7VvMGAQluc.jpg",
    img4: "./img/img_product/m7qbZc8EfJA.jpg",
    category: "Игрушки",
    subcategory_1: "modular",
    subcategory_2: "frame",
  },
  {
    id: "2",
    name: "Трактор Massey F ",
    price: ((80 / 100) * 80).toFixed(0),
    depth: "49 см.",
    width: "19 см.",
    height: "21 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Трактор выполнен реалистичной копией модели Massey Ferguson c погрузчиком.Кабина с открывающимися дверьми.
	 Встроенная амортизированная оси с гидравлическим приводом, позволяющая управлять колесами трактора рулем через двери или выдвигающимся мини-рулем через отрывающийся люк на крыше.
	 Подвесной капот открывает доступ к муляжу двигателя.
	 Вес: 1,4<br>`,
    img: "./img/maxi.jpg",
    img1: "./img/maxi.jpg",
    img2: "./img/img_product/69514036_355147265365419_7233966578354388877_n.jpg",
    img3: "./img/img_product/RT_E_kWPzWA.jpg",
    img4: "./img/img_product/-TUAkI9kkoI.jpg",
    category: "Игрушки",
    subcategory_1: "modular",
    subcategory_2: "frame",
  },
  {
    id: "3",
    name: "Трактор DU2000",
    price: ((26 / 100) * 80).toFixed(0),
    depth: "49 см.",
    width: "28 см.",
    height: "20 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Трактор выполнен реалистичной копией модели Трактора DU2000 c погрузчиком.Кабина с открывающимися дверьми.
	 Встроенная амортизированная оси с гидравлическим приводом, позволяющая управлять колесами трактора рулем через двери или выдвигающимся мини-рулем через отрывающийся люк на крыше.
	 Подвесной капот открывает доступ к муляжу двигателя.
	 Вес: 1,4`,
    img: "./img/krisha.jpg",
    img1: "./img/krisha.jpg",
    img2: "./img/img_product/03V4cIQXia4.jpg",
    img3: "./img/img_product/IUm_j8RYeC4.jpg",
    img4: "./img/img_product/h3l2DfI_rNE.jpg",
    category: "Игрушки",
    subcategory_1: "cap",
    subcategory_2: "no_slate_cap",
  },
  {
    id: "4",
    name: "Трактор Mu5S",
    price: ((60 / 100) * 80).toFixed(0),
    depth: "57 см.",
    width: "16 см.",
    height: "18 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Колёса поворачиваются дополнительным рулём.  Передняя ось оснащена амортизатором. Фаркоп.
	 Прицеп-самосвал откидывается и фиксируется в верхнем положении. Боковые и задние борта открываются. Оснащён опорой для устойчивого положения и тягово-сцепным устройством.
	 Колёса трактора и прицепа-самосвала прорезинены. В наборе трактор и прицеп-самосвал.
	  Вес: 1`,
    img: "./img/mini.png",
    img1: "./img/mini.png",
    img2: "./img/img_product/отобр8.jpg",
    img3: "./img/img_product/DSC02603.jpg",
    img4: "./img/img_product/69514036_355147265365419_7233966578354388877_n.jpg",
    category: "Игрушки",
    subcategory_1: "modular",
    subcategory_2: "no_frame",
  },
  {
    id: "5",
    name: "Трактор Fendt 209 S с прицепом",
    price: ((66 / 100) * 80).toFixed(0),
    depth: "57 см.",
    width: "16 см.",
    height: "18 см.",
    spaciousness: "",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Колёса поворачиваются дополнительным рулём.  Передняя ось оснащена амортизатором. Фаркоп.
	 Прицеп-самосвал откидывается и фиксируется в верхнем положении. Боковые и задние борта открываются. Оснащён опорой для устойчивого положения и тягово-сцепным устройством.
	 Колёса трактора и прицепа-самосвала прорезинены. В наборе трактор и прицеп-самосвал.
	  Вес: 1`,
    img: "./img/minidel.jpg",
    img1: "./img/minidel.jpg",
    img2: "./img/img_product/DSC_93191567.jpg",
    img3: "./img/img_product/DSC02603.jpg",
    img4: "./img/img_product/-TUAkI9kkoI.jpg",
    category: "Игрушки",
    subcategory_1: "modular",
    subcategory_2: "no_frame",
  },
  {
    id: "6",
    name: "Трактор John Deere c прицепом с манипулятором",
    price: ((14 / 100) * 80).toFixed(0),
    depth: "77 см.",
    width: "22 см.",
    height: "24 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Кабина из прозрачного и высококачественного пластика. Съемная передняя масса. Сцепление прицепа с подъемным механизмом с регулируемой высотой
	 Допуск для фронтального погрузчика. Открывающийся капот моторного отсека.	 Управляется с помощью дополнительного руля. Задний прицеп с краном-манипулятором.	 Заднее сцепное устройство
	 Внешний рычаг крана можно вытащить или сдвинуть назад в конечное положение.	В наборе трактор, прицеп, 4 бревна.
	 Вес: 2,5`,
    img: "./img/krishmini.jpg",
    img1: "./img/krishmini.jpg",
    img2: "./img/krishmini.jpg",
    img3: "./img/krishmini.jpg",
    img4: "./img/krishmini.jpg",
    category: "Игрушки",
    subcategory_1: "cap",
    subcategory_2: "slate_cap",
  },
  {
    id: "7",
    name: "Трактор John Deere 9620RX гусеничный",
    price: ((70 / 100) * 80).toFixed(0),
    depth: "58 см.",
    width: "20 см.",
    height: "26 см.",
    spaciousness: "48 л.",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Двери кабины открываются, позволяя рассмотреть кабину водителя. Капот открывается, предоставляя доступ к его двигателю.
	 Уменьшенная копия реального гусеничного трактора.	 Выполнен из прочной пластмассы. 	
	 Вес: 2,2.`,
    img: "./img/huge.jpg",
    img1: "./img/huge.jpg",
    img2: "./img/huge.jpg",
    img3: "./img/huge.jpg",
    img4: "./img/huge.jpg",
    category: "Игрушки",
    subcategory_1: "big",
    subcategory_2: "frame",
  },
  {
    id: "8",
    name: "Погрузчик John X258",
    price: 80,
    depth: "58 см.",
    width: "20 см.",
    height: "18 см.",
    spaciousness: "",
    material: "пластик",
    coating: "лак",
    description: `Колёса поворачиваются дополнительным рулём. Капот поднимается (открывается доступ к двигателю).	 Двери кабины открываются.
	 Передняя ось оснащена амортизатором. Фаркоп.
	 Вес: 2,2`,
    img: "./img/hugedel.jpg",
    img1: "./img/hugedel.jpg",
    img2: "./img/hugedel.jpg",
    img3: "./img/hugedel.jpg",
    img4: "./img/hugedel.jpg",
    category: "Игрушки",
    subcategory_1: "big",
    subcategory_2: "frame",
  },
  {
    id: "9",
    name: "Трактор JCB Fastrac 3220",
    price: 26,
    depth: "38 см.",
    width: "19 см.",
    height: "21 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Колёса поворачиваются дополнительным рулём. Капот поднимается (открывается доступ к двигателю).
	 Двери кабины открываются. Передняя ось оснащена амортизатором. Фаркоп.	 Колёса прорезинены.	 В наборе трактор.
	 Вес: 1,2`,
    img: "./img/krishhuge.jpg",
    img1: "./img/krishhuge.jpg",
    img2: "./img/krishhuge.jpg",
    img3: "./img/krishhuge.jpg",
    img4: "./img/krishhuge.jpg",
    category: "Игрушки",
    subcategory_1: "cap",
    subcategory_2: "slate_cap",
  },
  {
    id: "10",
    name: "Трактор John Deere с прицепом и фигуркой",
    price: 100,
    depth: "28 см.",
    width: "18 см.",
    height: "15 см.",
    spaciousness: " ",
    material: "пластик",
    coating: "лак",
    description: `Трактор John Deere с прицепом и фигуркой.`,
    img: "./img/bearsbox.png",
    img1: "./img/bearsbox.png",
    img2: "./img/bearsbox.jpg",
    img3: "./img/bearsbox.jpg",
    img4: "./img/bearsbox.jpg",
    category: "Игрушки",
    subcategory_1: "rest_box",
    subcategory_2: "no_frame",
  },
  {
    id: "11",
    name: "Трактор Claas Nectis 267 F",
    price: 29,
    depth: "27 см.",
    width: "15 см.",
    height: "18 см.",
    spaciousness: " ",
    material: "пластик",
    coating: "лак",
    description: `Модель 1:16. Колёса поворачиваются дополнительным рулём.	 Передняя ось оснащена амортизатором. Фаркоп.
	 Колёса прорезинены. В наборе трактор.
	  Вес: 0,5`,
    img: "./img/Pine.jpg",
    img1: "./img/Pine.jpg",
    img2: "./img/Pine.jpg",
    img3: "./img/Pine.jpg",
    img4: "./img/Pine.jpg",
    category: "Игрушки",
    subcategory_1: "rest_box",
    subcategory_2: "frame",
  },
  {
    id: "12",
    name: "Лебёдка",
    price: 36,
    depth: "13 см.",
    width: "10 см.",
    height: "20 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Лебедка совместима со всеми внедорожниками (кроме арт.02-540), а также с машинами Mercedes-Benz Sprinter, Mack, Scania и Man (при наличии специального адаптера)`,
    img: "./img/karandasnica.jpg",
    img1: "./img/karandasnica.jpg",
    img2: "./img/karandasnica.jpg",
    img3: "./img/karandasnica.jpg",
    img4: "./img/karandasnica.jpg",
    category: "Аксессуары",
    subcategory_1: "pencil_box",
  },
  {
    id: "13",
    name: "Кэмбриджский каток",
    price: 30,
    depth: "29 см.",
    width: "16 см.",
    height: "12 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "-",
    description: `Кэмбриджский каток для тракторов. Особенности: Данный аксессуар используется в сельском хозяйстве для взрыхления или уплотнения земли, поэтому дети смогут повторить эти манипуляции в ходе игры с трактором.
	 Каток крепится к игрушке с помощью фаркопа. Аксессуар выполнен из пластика повышенной прочности, окрашенного насыщенными и нетоксичными красителями.
	 Каток поможет разнообразить игры ребенка с трактором из серии Bruder
	 Вес: 0,2.`,
    img: "./img/karandasnica_3.jpg",
    img1: "./img/karandasnica_3.jpg",
    img2: "./img/karandasnica_3.jpg",
    img3: "./img/karandasnica_3.jpg",
    img4: "./img/karandasnica_3.jpg",
    category: "Остальные товары",
    subcategory_1: "pencil_box",
  },
  {
    id: "14",
    name: "Упаковщик рулонов сена",
    price: 45,
    depth: "40 см.",
    width: "15 см.",
    height: "17 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "-",
    description: `Упаковщик рулонов сена
	 Особенности: подъемник для загрузки тюка соломы на упаковочный стол;
	 поворотная платформа с функцией вращения во время движения (имитация процесса намотки);
	 два муляжа тюков (солома и упаковка);
	 вращение тюка в двух плоскостях – вертикальной и горизонтальной;
	 наклон упаковочной платформы для сброса готового тюка;
	 регулируемое положение сцепного устройства;
	 колеса с протекторными шинами;
	 материал изготовления – высокотехнологичный пластик;
	 Вес: 0,7 кг .`,
    img: "./img/karandashnica_5.jpg",
    img2: "./img/karandashnica_5.jpg",
    img2: "./img/karandashnica_5.jpg",
    img3: "./img/karandashnica_5.jpg",
    img4: "./img/karandashnica_5.jpg",
    category: "Остальные товары",
    subcategory_1: "pencil_box",
  },
  {
    id: "15",
    name: "Самосвал MAN c 3 мусорными контейнерами",
    price: 90,
    depth: "58 см.",
    width: "19 см.",
    height: "30 см.",
    spaciousness: "60 л.",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Окна кабины из прозрачного пластика. Наружные зеркала складываются. Двери открываются. Стрела может поворачиваться на 360, выдвигается и фиксируется в любом положении.
	 Боковые стенки складываются с 3 -х сторон. Профильные прорезиненные шины. В наборе самосвал, мусорные контейнеры.
	 Вес: 2,7 `,
    img: "./img/open.jpg",
    img1: "./img/open.jpg",
    img2: "./img/open.jpg",
    img3: "./img/open.jpg",
    img4: "./img/open.jpg",
    category: "Игрушки",
    subcategory_1: "rack",
    subcategory_2: "open",
  },
  {
    id: "16",
    name: "Самосвал Mercedes-Benz с мини погрузчиком",
    price: 100,
    depth: "58 см.",
    width: "19 см.",
    height: "22 см.",
    spaciousness: "60 л.",
    material: "пластик",
    coating: "лак",
    description: `Особенности: линзы кабины из прозрачного и небьющегося пластика.Складывающиеся наружные зеркала. Двери для открывания, контейнер можно откинуть назад
	 две откидные двери на контейнере, кабина экскаватора может поворачиваться на 360 °	 регулируемая, наклоняемая и блокируемая высота ножа плуга,	 полностью функциональный рычаг экскаватора
	 Вес: 2,6.`,
    img: "./img/sdel.jpg",
    img1: "./img/sdel.jpg",
    img2: "./img/sdel.jpg",
    img3: "./img/sdel.jpg",
    img4: "./img/sdel.jpg",
    category: "Игрушки",
    subcategory_1: "rack",
    subcategory_2: "with_divisions",
  },
  {
    id: "17",
    name: "Самосвал Mercedes-Benz",
    price: 94,
    depth: "55 см.",
    width: "19 см.",
    height: "23 см.",
    spaciousness: " ",
    material: "пластик",
    coating: "лак",
    description: `Особенности: открывающиеся двери; наружные складные зеркала; откидной кузов; протектора на шинах;
	 возможность установления светового и звукового модулей; посадка водителя за руль самосвала.
	 Вес: 2.3 кг.`,
    img: "./img/clouse.jpg",
    img1: "./img/clouse.jpg",
    img2: "./img/clouse.jpg",
    img3: "./img/clouse.jpg",
    img4: "./img/clouse.jpg",
    category: "Игрушки",
    subcategory_1: "rack",
    subcategory_2: "close",
  },
  {
    id: "18",
    name: "Бетономешалка Scania (цвет жёлто синий)",
    price: 120,
    depth: "66 см.",
    width: "19 см.",
    height: "29 см.",
    spaciousness: "-",
    material: "берёза",
    coating: "восковый лак",
    description: `Особенности: Двери водительской кабины открываются, зеркала складываются, сзади автомобиля установлена лестница с площадкой
	 На бочке возле водительской кабины расположена ручка, которая крутит смеситель в разные стороны для загрузки – разгрузки.	 В смеситель можно насыпать лёгкие сыпучие вещества
	 Желоб для раствора удлиняется до пола и поворачивается на 180° Колёса прорезинены.	 В наборе бетономешалка.
	 Вес: 2,7`,
    img: "./img/book_floor.png",
    img1: "./img/book_floor.png",
    img2: "./img/book_floor.png",
    img3: "./img/book_floor.png",
    img4: "./img/book_floor.png",
    category: "Игрушки",
    subcategory_1: "shelf",
    subcategory_2: "outdoor",
  },
  {
    id: "19",
    name: "Бетономешалка Scania (цвет жёлто синий)",
    price: 110,
    depth: "66 см.",
    width: "19 см.",
    height: "29 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Двери водительской кабины открываются, зеркала складываются, сзади автомобиля установлена лестница с площадкой
	 На бочке возле водительской кабины расположена ручка, которая крутит смеситель в разные стороны для загрузки – разгрузки.	 В смеситель можно насыпать лёгкие сыпучие вещества
	 Желоб для раствора удлиняется до пола и поворачивается на 180° Колёса прорезинены.	 В наборе бетономешалка.
	 Вес: 2,7`,
    img: "./img/book_wall.png",
    img1: "./img/book_wall.png",
    img2: "./img/book_wall.png",
    img3: "./img/book_wall.png",
    img4: "./img/book_wall.png",
    category: "Игрушки",
    subcategory_1: "shelf",
    subcategory_2: "wall_mounted",
  },
  {
    id: "20",
    name: "Погрузчик колёсный CAT с ковшом",
    price: 70,
    depth: "38 см.",
    width: "16 см.",
    height: "18 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Телескопическая стрела погрузчика выезжает, благодаря специальной ручке.
	 Стрела меняет угол наклона до 60°.	 Водительская дверь открывается, зеркало заднего вида складывается.
	 Фаркоп. Колёса прорезинены. Ковш можно легко заменить на другие аксессуары, поставляемые отдельно.
	 В наборе колёсный погрузчик с телескопическим ковшом.
	 Вес: 0,8`,
    img: "./img/grif.jpg",
    img1: "./img/grif.jpg",
    img2: "./img/grif.jpg",
    img3: "./img/grif.jpg",
    img4: "./img/grif.jpg",
    category: "Игрушкиc",
    subcategory_2: "big_board",
  },
  {
    id: "21",
    name: "Экскаватор JCB 8010...",
    price: 90,
    depth: "38 см.",
    width: "16 см.",
    height: "13 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `собенности: Платформа гусеничного мини-экскаватора поворачивается на 360°.
	 Мини-экскаватор оснащён отвалом. Экскаватором легко копать держась за его стрелу.
	 В наборе мини экскаватор!`,
    img: "./img/raketa.jpg",
    img1: "./img/raketa.jpg",
    img2: "./img/raketa.jpg",
    img3: "./img/raketa.jpg",
    img4: "./img/raketa.jpg",
    category: "Игрушки",
    subcategory_1: "no_magnetic",
    subcategory_2: "big_board",
  },
  {
    id: "22",
    name: "Погрузчик колёсный CAT с ковшом",
    price: 50,
    depth: "38 см.",
    width: "16 см.",
    height: "18 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Рукав с ковшом полностью регулируемые, могут подниматься, а также менять угол наклона
	 Передний ковш съемный Многофункциональный загрузочный рукав. В наборе погрузчик.
	 Вес: 0,7`,
    img: "./img/grifStarbd.jpg",
    img1: "./img/grifStarbd.jpg",
    img2: "./img/grifStarbd.jpg",
    img3: "./img/grifStarbd.jpg",
    img4: "./img/grifStarbd.jpg",
    category: "Игрушки",
    subcategory_1: "magnetic",
    subcategory_2: "small_board",
  },
  {
    id: "23",
    name: "Погрузчик SX42",
    price: 46,
    depth: "39 см.",
    width: "18 см.",
    height: "16 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Особенности: Рукав с ковшом полностью регулируемые, могут подниматься, а также менять угол наклона
	 Передний ковш съемный Многофункциональный загрузочный рукав. В наборе погрузчик.
	 Вес: 0,7!`,
    img: "./img/grifShar.jpg",
    img1: "./img/grifShar.jpg",
    img2: "./img/grifShar.jpg",
    img3: "./img/grifShar.jpg",
    img4: "./img/grifShar.jpg",
    category: "Игрушки",
    subcategory_1: "no_magnetic",
    subcategory_2: "small_board",
  },
  {
    id: "24",
    name: "экскаватор JCB 8010 CTS",
    price: 40,
    depth: "59 см.",
    width: "18 см.",
    height: "19 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Платформа гусеничного мини-экскаватора поворачивается на 360°.
	 Мини-экскаватор оснащён отвалом.
	 Экскаватором легко копать держась за его стрелу.
	 В наборе мини экскаватор!
	 вес: 1,2`,
    img: "./img/grisSova.jpg",
    img1: "./img/grisSova.jpg",
    img2: "./img/grisSova.jpg",
    img3: "./img/grisSova.jpg",
    img4: "./img/grisSova.jpg",
    category: "Игрушки",
    subcategory_1: "magnetic",
    subcategory_2: "small_board",
  },
  {
    id: "25",
    name: "Погрузчик гусеничный CAT с ковшом",
    price: 50,
    depth: "56 см.",
    width: "19 см.",
    height: "25 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Гусеничный погрузчик оснащён ковшом, который поднимается вверх/вниз и фиксируется в верхнем положении
	 Угол наклона ковша регулируется и фиксируется в двух положениях, чтобы избежать просыпания сыпучих грузов
	 Трёхзубчатый разрыхлитель погрузчика можно устанавливается в положениях – рыхление, зависание
	 Двери водительской кабины открываются
	 Гусеницы пластмассовые`,
    img: "./img/grifclas.jpg",
    img1: "./img/grifclas.jpg",
    img2: "./img/grifclas.jpg",
    img3: "./img/grifclas.jpg",
    img4: "./img/grifclas.jpg",
    category: "Игрушки",
    subcategory_1: "no_magnetic",
    subcategory_2: "small_board",
  },
  {
    id: "26",
    name: "Аксессуары: Посевная машина Amazone",
    price: 40,
    depth: "7 см.",
    width: "10 см.",
    height: "5 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Характеристики:
	 сельскохозяйственный агрегат для посева семян выполнен с учетом всех основных характеристик реального механизма:
	 бункер для семян (можно заполнить зерном); крышка бункера открывается;
	 сеялка во время движения полностью функционирует;  
	 Вес: 0,4 кг`,
    img: "./img/bufet.jpg",
    img1: "./img/bufet.jpg",
    img2: "./img/bufet.jpg",
    img3: "./img/bufet.jpg",
    img4: "./img/bufet.jpg",
    category: "Аксессуары",
    subcategory_1: "toy_furniture",
  },
  {
    id: "27",
    name: "Аксессуары: снегоочиститель",
    price: 50,
    depth: "10 см.",
    width: "7 см.",
    height: "4 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Масштаб 1:16 Регулируемый и запираемый по высоте.  Вес: 0,5 `,
    img: "./img/krovat.jpg",
    img1: "./img/krovat.jpg",
    img2: "./img/krovat.jpg",
    img3: "./img/krovat.jpg",
    img4: "./img/krovat.jpg",
    category: "Аксессуары",
    subcategory_1: "toy_furniture",
  },
  {
    id: "28",
    name: "Фронтальный почвоуплотнитель LEMKEN VarioPack ",
    price: 30,
    depth: "10 см.",
    width: "7 см.",
    height: "5 см.",
    spaciousness: "-",
    material: "пластик",
    coating: "лак",
    description: `Фронтальный почвоуплотнитель Lemken VarioPack K
	 Особенности: сохранение всех функций реально действующего агрегата;
	 возможность установки спереди или сзади трактора;
	 два положения рычагов – рабочее и транспортное (поднимаются вертикально под углом 90 градусов);.`,
    img: "./img/stol.jpg",
    img1: "./img/stol.jpg",
    img2: "./img/stol.jpg",
    img3: "./img/stol.jpg",
    img4: "./img/stol.jpg",
    category: "Аксессуары",
    subcategory_1: "toy_furniture",
  },
  {
    id: "29",
    name: "Шины для системы сдвоенных колёс с серыми дисками 4шт.",
    price: 15,
    depth: "5 см.",
    width: "5 см.",
    height: "5 см.",
    spaciousness: "-",
    material: "-",
    coating: "-",
    description: `Шины для системы сдвоенных колёс с серыми дисками 4шт.!`,
    img: "./img/kalesa.png",
    img1: "./img/kalesa.png",
    img2: "./img/kalesa.png",
    img3: "./img/kalesa.png",
    img4: "./img/kalesa.png",
    category: "Аксессуары",
    subcategory_1: "furniture",
  },
  {
    id: "30",
    name: "Отвал регулируемый по высоте",
    price: 5,
    depth: "5 см.",
    width: "2 см.",
    height: "3 см.",
    spaciousness: "-",
    material: "-",
    coating: "-",
    description: `отвал регулируемый по высоте`,
    img: "./img/pod.jpg",
    img1: "./img/pod.jpg",
    img2: "./img/pod.jpg",
    img3: "./img/pod.jpg",
    img4: "./img/pod.jpg",
    category: "Аксессуары",
    subcategory_1: "furniture",
  },
  {
    id: "31",
    name: "Лошади в ассортименте",
    price: 5,
    price: "5",
    depth: "10 см.",
    width: "2 см.",
    height: "5 см.",
    spaciousness: "-",
    material: "-",
    coating: "-",
    description: `Лошади в ассортименте`,
    img: "./img/melki.jpg",
    img1: "./img/melki.jpg",
    img2: "./img/melki.jpg",
    img3: "./img/melki.jpg",
    img4: "./img/melki.jpg",
    category: "Аксессуары",
    subcategory_1: "crayons",
  },
];
